param(
  [string]$InstallDir = 'C:\ProgramData\VantixGC\Restaurant-P15-Lab',
  [string]$AdminPassword = '',
  [switch]$EnableLan,
  [string]$LanAddress = '',
  [string]$LanCidr = '',
  [string]$BackupUploadUrl = '',
  [string]$BackupUploadToken = '',
  [switch]$NoServices,
  [switch]$NoShortcut,
  [switch]$NoFirewall
)

$ErrorActionPreference='Stop'
$HttpPort=8815; $PgPort=55435; $PrintPort=18815
$Database='vantix_restaurant_p15_lab'; $DbUser='vantix_p15'
$Tenant='demo-restaurante'; $InstallationId='HOME-PILOT-P15'
$PgService='VantixGC Restaurant P15 PostgreSQL'
$ServerServiceId='VantixRestaurantP15Server'; $PrintServiceId='VantixRestaurantP15Print'; $BackupServiceId='VantixRestaurantP15Backup'
$PackageRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..\..'))
$Payload=Join-Path $PackageRoot 'payload'; $InstallDir=[IO.Path]::GetFullPath($InstallDir).TrimEnd('\')
$AppDir=Join-Path $InstallDir 'app'; $RuntimeDir=Join-Path $InstallDir 'runtime'; $PgRoot=Join-Path $InstallDir 'postgres'; $PgBin=Join-Path $PgRoot 'bin'; $PgData=Join-Path $InstallDir 'data\postgres'
$ConfigDir=Join-Path $InstallDir 'config'; $SecretsDir=Join-Path $InstallDir 'secrets'; $LogsDir=Join-Path $InstallDir 'logs'; $BackupDir=Join-Path $InstallDir 'backups'; $ServicesDir=Join-Path $InstallDir 'services'; $FilesDir=Join-Path $InstallDir 'files'
$EnvFile=Join-Path $ConfigDir '.env'; $DbSecretFile=Join-Path $SecretsDir 'db-password.txt'; $JwtFile=Join-Path $SecretsDir 'jwt-secret.txt'; $BackupSecretFile=Join-Path $SecretsDir 'backup-key.txt'; $PrintTokenFile=Join-Path $SecretsDir 'print-token.txt'

function Assert-Admin { $id=[Security.Principal.WindowsIdentity]::GetCurrent(); $p=New-Object Security.Principal.WindowsPrincipal($id); if(-not $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)){throw 'Ejecuta el instalador P15 como Administrador.'} }
function New-Secret([int]$Length=48){ $s=([guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N')); return $s.Substring(0,[Math]::Min($Length,$s.Length)) }
function Protect-Secret([string]$Path){ & icacls.exe $Path /inheritance:r /grant:r '*S-1-5-18:(F)' '*S-1-5-32-544:(F)' | Out-Null; $global:LASTEXITCODE=0 }
function Copy-Tree([string]$Source,[string]$Destination){ if(-not(Test-Path $Source)){throw "Falta payload: $Source"}; New-Item -ItemType Directory -Force -Path $Destination|Out-Null; & robocopy.exe $Source $Destination /MIR /COPY:DAT /DCOPY:DAT /R:2 /W:1 /NFL /NDL /NJH /NJS /NP|Out-Null; if($LASTEXITCODE -gt 7){throw "Robocopy fallo copiando $Source"}; $global:LASTEXITCODE=0 }
function Assert-Port([int]$Port){ $x=@(Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue); if($x.Count){ $ours=$false; foreach($r in $x){$p=Get-CimInstance Win32_Process -Filter "ProcessId=$($r.OwningProcess)" -ErrorAction SilentlyContinue; if($p.ExecutablePath -and $p.ExecutablePath.StartsWith($InstallDir,[StringComparison]::OrdinalIgnoreCase)){$ours=$true}}; if(-not $ours){throw "Puerto P15 $Port ocupado por otro proceso."} } }
function Get-Lan { if(-not $EnableLan){return @{enabled=$false;bind='127.0.0.1';address='127.0.0.1';cidr=''}}; $addr=$LanAddress; $cidr=$LanCidr; if(-not $addr){ $route=Get-NetRoute -AddressFamily IPv4 -DestinationPrefix '0.0.0.0/0' -ErrorAction SilentlyContinue|Sort-Object RouteMetric,InterfaceMetric|Select-Object -First 1; if($route){$ip=Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $route.InterfaceIndex -AddressState Preferred -ErrorAction SilentlyContinue|Where-Object{$_.IPAddress -match '^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.)'}|Select-Object -First 1; if($ip){$addr=$ip.IPAddress; if(-not $cidr){$parts=$addr.Split('.'); $cidr="$($parts[0]).$($parts[1]).$($parts[2]).0/24"}}} }; if(-not $addr -or -not $cidr){throw 'No se pudo detectar LAN privada. Usa -LanAddress y -LanCidr.'}; return @{enabled=$true;bind='0.0.0.0';address=$addr;cidr=$cidr} }
function Wait-Tcp([int]$Port,[int]$Seconds=60){ for($i=0;$i -lt $Seconds;$i++){ if(Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue){return $true}; Start-Sleep 1 }; return $false }
function Write-WinSw([string]$Id,[string]$Display,[string]$Description,[string]$Script,[hashtable]$ExtraEnv){ $exe=Join-Path $ServicesDir "$Id.exe"; Copy-Item (Join-Path $Payload 'winsw\WinSW.exe') $exe -Force; $xml=Join-Path $ServicesDir "$Id.xml"; $envXml=@("<env name=\"P15_ENV_FILE\" value=\"$EnvFile\" />"); foreach($k in $ExtraEnv.Keys){$v=[Security.SecurityElement]::Escape([string]$ExtraEnv[$k]);$envXml += "<env name=\"$k\" value=\"$v\" />"}; $node=Join-Path $RuntimeDir 'node.exe'; $scriptPath=Join-Path $AppDir $Script; $content=@"
<service>
  <id>$Id</id><name>$Display</name><description>$Description</description>
  <executable>$node</executable><arguments>\"$scriptPath\"</arguments><workingdirectory>$AppDir</workingdirectory>
  $($envXml -join "`r`n  ")
  <startmode>Automatic</startmode><delayedAutoStart>true</delayedAutoStart><stoptimeout>20sec</stoptimeout>
  <onfailure action=\"restart\" delay=\"5 sec\"/><onfailure action=\"restart\" delay=\"15 sec\"/><onfailure action=\"restart\" delay=\"30 sec\"/>
  <logpath>$LogsDir</logpath><log mode=\"roll-by-size-time\"><sizeThreshold>10485760</sizeThreshold><pattern>yyyyMMdd</pattern><autoRollAtTime>00:00:00</autoRollAtTime><zipOlderThanNumDays>7</zipOlderThanNumDays></log>
</service>
"@; Set-Content -LiteralPath $xml -Value $content -Encoding UTF8; return $exe }

Assert-Admin
if($InstallDir.StartsWith('C:\ProgramData\VantixGC\Edge',[StringComparison]::OrdinalIgnoreCase) -or $InstallDir -match 'Restaurant-P1[34]'){throw 'P15 no puede instalarse dentro de Edge/P13/P14.'}
Assert-Port $HttpPort; Assert-Port $PgPort; Assert-Port $PrintPort
$lan=Get-Lan
foreach($d in @($InstallDir,$ConfigDir,$SecretsDir,$LogsDir,$BackupDir,$ServicesDir,$FilesDir,(Join-Path $InstallDir 'data'))){New-Item -ItemType Directory -Force -Path $d|Out-Null}
Copy-Tree (Join-Path $Payload 'app') $AppDir; Copy-Tree (Join-Path $Payload 'runtime') $RuntimeDir; Copy-Tree (Join-Path $Payload 'postgres') $PgRoot; Copy-Tree (Join-Path $Payload 'winsw') (Join-Path $InstallDir 'winsw')
$freshDb=-not(Test-Path (Join-Path $PgData 'PG_VERSION'))
if(-not(Test-Path $DbSecretFile)){New-Secret 48|Set-Content $DbSecretFile -NoNewline -Encoding ASCII;Protect-Secret $DbSecretFile}; if(-not(Test-Path $JwtFile)){New-Secret 64|Set-Content $JwtFile -NoNewline -Encoding ASCII;Protect-Secret $JwtFile}; if(-not(Test-Path $BackupSecretFile)){New-Secret 64|Set-Content $BackupSecretFile -NoNewline -Encoding ASCII;Protect-Secret $BackupSecretFile}; if(-not(Test-Path $PrintTokenFile)){New-Secret 48|Set-Content $PrintTokenFile -NoNewline -Encoding ASCII;Protect-Secret $PrintTokenFile}
$dbPass=(Get-Content $DbSecretFile -Raw).Trim(); $jwt=(Get-Content $JwtFile -Raw).Trim(); $backupSecret=(Get-Content $BackupSecretFile -Raw).Trim(); $printToken=(Get-Content $PrintTokenFile -Raw).Trim()
if($freshDb){New-Item -ItemType Directory -Force -Path $PgData|Out-Null; $pw=Join-Path $SecretsDir 'pg-init.txt';$dbPass|Set-Content $pw -NoNewline -Encoding ASCII;Protect-Secret $pw; & (Join-Path $PgBin 'initdb.exe') -D $PgData -U $DbUser --pwfile=$pw --auth=scram-sha-256 --encoding=UTF8 --locale=C; if($LASTEXITCODE){throw 'initdb P15 fallo.'};Remove-Item $pw -Force}
$pgConf=Join-Path $PgData 'postgresql.conf'; $pgText=Get-Content $pgConf -Raw; $pgText=[regex]::Replace($pgText,'(?m)^\s*listen_addresses\s*=.*$','');$pgText=[regex]::Replace($pgText,'(?m)^\s*port\s*=.*$','');$pgText += "`r`n# VantixGC P15`r`nlisten_addresses='127.0.0.1'`r`nport=$PgPort`r`nmax_connections=100`r`nshared_buffers=256MB`r`nwal_level=replica`r`narchive_mode=on`r`narchive_command='cmd /c if not exist \"$($BackupDir.Replace('\','/'))/wal/%f\" copy \"%p\" \"$($BackupDir.Replace('\','/'))/wal/%f\" >NUL'`r`n";Set-Content $pgConf $pgText -Encoding ASCII;New-Item -ItemType Directory -Force -Path (Join-Path $BackupDir 'wal')|Out-Null
if(-not $NoServices){ try{Stop-Service -Name $PgService -ErrorAction SilentlyContinue}catch{}; & (Join-Path $PgBin 'pg_ctl.exe') unregister -N $PgService 2>$null | Out-Null; $global:LASTEXITCODE=0; & (Join-Path $PgBin 'pg_ctl.exe') register -N $PgService -D $PgData -S auto -U 'NT AUTHORITY\LocalService' -o "-p $PgPort"; if($LASTEXITCODE){throw 'No se pudo registrar PostgreSQL P15 como servicio.'}; Start-Service -Name $PgService } else { & (Join-Path $PgBin 'pg_ctl.exe') -D $PgData -l (Join-Path $LogsDir 'postgres.log') -w start }
if(-not(Wait-Tcp $PgPort 60)){throw 'PostgreSQL P15 no inicio en 55435.'}
$env:PGPASSWORD=$dbPass; $exists=(& (Join-Path $PgBin 'psql.exe') -h 127.0.0.1 -p $PgPort -U $DbUser -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$Database'" 2>$null|Select-Object -First 1).Trim(); if($exists -ne '1'){& (Join-Path $PgBin 'createdb.exe') -h 127.0.0.1 -p $PgPort -U $DbUser $Database; if($LASTEXITCODE){throw 'createdb P15 fallo.'}}
$enc=[Uri]::EscapeDataString($dbPass); $dbUrl="postgresql://$DbUser`:$enc@127.0.0.1`:$PgPort/$Database"; $runtimeCfg=[ordered]@{product='VantixGC Restaurant P15';installationId=$InstallationId;tenant=$Tenant;httpPort=$HttpPort;postgresPort=$PgPort;database=$Database;lan=$lan;printPort=$PrintPort;authority='LOCAL_PRIMARY'};$runtimeCfg|ConvertTo-Json -Depth 8|Set-Content (Join-Path $ConfigDir 'runtime.json') -Encoding UTF8;if(-not(Test-Path (Join-Path $ConfigDir 'printers.json'))){'{"version":1,"stations":{}}'|Set-Content (Join-Path $ConfigDir 'printers.json') -Encoding UTF8}
$envLines=@("P15_ENABLED=true","P15_INSTALLATION_ID=$InstallationId","P15_TENANT_SUBDOMAIN=$Tenant","P15_HTTP_PORT=$HttpPort","P15_BIND_HOST=$($lan.bind)","P15_ADVERTISE_HOST=$($lan.address)","P15_LAN_ENABLED=$($lan.enabled.ToString().ToLowerInvariant())","P15_LAN_CIDR=$($lan.cidr)","P15_PRINT_PORT=$PrintPort","P15_INSTALL_DIR=$InstallDir","P15_PG_BIN=$PgBin","P15_BACKUP_DIR=$BackupDir","P15_BACKUP_ENABLED=true","P15_BACKUP_INTERVAL_MINUTES=15","P15_BACKUP_KEEP=48","P15_BACKUP_UPLOAD_URL=$BackupUploadUrl","P15_BACKUP_UPLOAD_TOKEN=$BackupUploadToken","DATABASE_URL=$dbUrl","P15_JWT_SECRET=$jwt","P15_BACKUP_SECRET=$backupSecret","NODE_ENV=production","DIAN_EMBEDDED_WORKER_ENABLED=false","NOTIFICATION_EMBEDDED_WORKER_ENABLED=false","PUBLIC_TENANT_REGISTRATION_ENABLED=false");$envLines|Set-Content $EnvFile -Encoding UTF8;Protect-Secret $EnvFile
Get-Content $EnvFile|ForEach-Object{if($_ -match '^([^=]+)=(.*)$'){[Environment]::SetEnvironmentVariable($matches[1],$matches[2],'Process')}}
$node=Join-Path $RuntimeDir 'node.exe';$prisma=Join-Path $AppDir 'node_modules\prisma\build\index.js';Push-Location $AppDir;try{& $node $prisma db push;if($LASTEXITCODE){throw 'Prisma db push P15 fallo.'}; if($freshDb){if(-not $AdminPassword){$AdminPassword='P15-'+(New-Secret 20)};$env:P15_ADMIN_PASSWORD=$AdminPassword;& $node (Join-Path $AppDir 'lab\restaurant-p15\bootstrap-demo.js');if($LASTEXITCODE){throw 'Bootstrap P15 fallo.'};Remove-Item Env:P15_ADMIN_PASSWORD -ErrorAction SilentlyContinue}}finally{Pop-Location}
if(-not $NoServices){ foreach($id in @($ServerServiceId,$PrintServiceId,$BackupServiceId)){ $old=Join-Path $ServicesDir "$id.exe"; if(Test-Path $old){& $old stop 2>$null|Out-Null;& $old uninstall 2>$null|Out-Null;$global:LASTEXITCODE=0} }; $serverExe=Write-WinSw $ServerServiceId 'VantixGC Restaurant P15 Server' 'Servidor local-primary del restaurante.' 'lab\restaurant-p15\runtime.js' @{P15_ENV_FILE=$EnvFile};$printExe=Write-WinSw $PrintServiceId 'VantixGC Restaurant P15 Print' 'Spooler local ESC/POS.' 'edge\print-spooler\server.js' @{SPOOLER_HOST='127.0.0.1';SPOOLER_PORT=$PrintPort;SPOOLER_SHARED_TOKEN=$printToken};$backupExe=Write-WinSw $BackupServiceId 'VantixGC Restaurant P15 Backup' 'Backup cifrado local y remoto desacoplado.' 'lab\restaurant-p15\backup-agent.js' @{P15_INSTALL_DIR=$InstallDir;P15_INSTALLATION_ID=$InstallationId;P15_TENANT_SUBDOMAIN=$Tenant;P15_PG_BIN=$PgBin;P15_BACKUP_DIR=$BackupDir;P15_BACKUP_SECRET=$backupSecret;P15_BACKUP_UPLOAD_URL=$BackupUploadUrl;P15_BACKUP_UPLOAD_TOKEN=$BackupUploadToken;DATABASE_URL=$dbUrl;P15_BACKUP_INTERVAL_MINUTES='15';P15_BACKUP_KEEP='48'}; foreach($exe in @($serverExe,$printExe,$backupExe)){& $exe install;if($LASTEXITCODE){throw "WinSW install fallo: $exe"}; & $exe start;if($LASTEXITCODE){throw "WinSW start fallo: $exe"}} }
if(-not $NoFirewall -and $lan.enabled){Get-NetFirewallRule -DisplayName 'VantixGC Restaurant P15 LAN 8815' -ErrorAction SilentlyContinue|Remove-NetFirewallRule;New-NetFirewallRule -DisplayName 'VantixGC Restaurant P15 LAN 8815' -Direction Inbound -Action Allow -Protocol TCP -LocalPort $HttpPort -RemoteAddress $lan.cidr -Profile Private|Out-Null}
if(-not $NoServices -and -not(Wait-Tcp $HttpPort 90)){throw 'Servidor P15 no inicio en 8815.'}
if(-not $NoShortcut){$url="http://$($lan.address):$HttpPort/app/centro-de-control-v2";$shell=New-Object -ComObject WScript.Shell;$shortcut=$shell.CreateShortcut((Join-Path ([Environment]::GetFolderPath('Desktop')) 'VantixGC Restaurante P15.lnk'));$shortcut.TargetPath="$env:SystemRoot\System32\cmd.exe";$shortcut.Arguments="/c start $url";$shortcut.WorkingDirectory=$InstallDir;$shortcut.Save()}
Write-Host '';Write-Host 'P15 INSTALADO' -ForegroundColor Green;Write-Host "URL: http://$($lan.address):$HttpPort/app/centro-de-control-v2";Write-Host "PostgreSQL: 127.0.0.1:$PgPort/$Database";Write-Host 'Servicios: PostgreSQL + Server + Print + Backup';Write-Host "Backup local: $BackupDir";if($freshDb){Write-Host '';Write-Host 'CREDENCIALES LAB (guardar):' -ForegroundColor Yellow;Write-Host "Usuarios: admin/mesero/cocina/barra/postres/cajero @demo-restaurante.vantixgc.com";Write-Host "Password: $AdminPassword";Write-Host "Recovery key: $backupSecret"}
