const fs = require('node:fs');
const fsp = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');
const { spawn } = require('node:child_process');

function exec(command,args,options={}){return new Promise((resolve,reject)=>{const p=spawn(command,args,{stdio:'pipe',windowsHide:true,...options});let out='',err='';p.stdout?.on('data',d=>out+=d);p.stderr?.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>code===0?resolve({out,err}):reject(Object.assign(new Error(err||`${command} exited ${code}`),{code:`EXIT_${code}`})))})}
async function sha256File(file){const h=crypto.createHash('sha256'),s=fs.createReadStream(file);for await(const chunk of s)h.update(chunk);return h.digest('hex')}
async function copyIfExists(src,dst){try{await fsp.mkdir(path.dirname(dst),{recursive:true});await fsp.copyFile(src,dst);return true}catch(e){if(e.code==='ENOENT')return false;throw e}}

class EdgeUpdater {
  constructor({central,store,appRoot=path.resolve(__dirname,'..'),dataDir,healthUrl,enabled=false}){
    this.central=central;this.store=store;this.appRoot=appRoot;this.dataDir=dataDir||path.join(appRoot,'data');this.healthUrl=healthUrl;this.enabled=Boolean(enabled);this.running=false;
  }
  async report(deploymentId,state,extra={}){try{await this.central('/edge/api/v1/update/report',{method:'POST',body:JSON.stringify({deploymentId,state,...extra})})}catch{}}
  async manifest(){return (await this.central('/edge/api/v1/update/manifest')).data}
  async backup(deploymentId,currentVersion){const root=path.join(this.dataDir,'backups',`${Date.now()}-${currentVersion||'unknown'}`);await fsp.mkdir(root,{recursive:true});await copyIfExists(process.env.EDGE_DB_PATH||path.join(this.dataDir,'vantixgc-edge.sqlite'),path.join(root,'vantixgc-edge.sqlite'));await copyIfExists(path.join(this.appRoot,'.env'),path.join(root,'.env'));await copyIfExists(path.join(this.appRoot,'version.json'),path.join(root,'version.json'));await this.report(deploymentId,'BACKUP',{backupPath:root,evidence:{currentVersion}});return root}
  async download(url,dest){const r=await fetch(url,{signal:AbortSignal.timeout(Number(process.env.EDGE_UPDATE_DOWNLOAD_TIMEOUT_MS||120000))});if(!r.ok)throw new Error(`Descarga update HTTP ${r.status}`);await fsp.mkdir(path.dirname(dest),{recursive:true});const file=fs.createWriteStream(dest);for await(const chunk of r.body)file.write(chunk);await new Promise((resolve,reject)=>file.end(e=>e?reject(e):resolve()));}
  async extract(zip,dest){await fsp.rm(dest,{recursive:true,force:true});await fsp.mkdir(dest,{recursive:true});if(process.platform==='win32')await exec('powershell.exe',['-NoProfile','-NonInteractive','-Command',`Expand-Archive -LiteralPath '${zip.replace(/'/g,"''")}' -DestinationPath '${dest.replace(/'/g,"''")}' -Force`]);else await exec('unzip',['-q','-o',zip,'-d',dest]);}
  async healthCheck(url=this.healthUrl){if(!url)return true;const end=Date.now()+Number(process.env.EDGE_UPDATE_HEALTH_TIMEOUT_MS||30000);let last;while(Date.now()<end){try{const r=await fetch(url,{signal:AbortSignal.timeout(3000)});if(r.ok)return true;last=new Error(`Health HTTP ${r.status}`)}catch(e){last=e}await new Promise(r=>setTimeout(r,1500))}throw last||new Error('Health check falló')}
  async atomicInstall(staged,deployment){const releases=path.join(this.appRoot,'releases'),target=path.join(releases,deployment.targetVersion),currentLink=path.join(this.appRoot,'current');await fsp.mkdir(releases,{recursive:true});await fsp.rm(target,{recursive:true,force:true});await fsp.rename(staged,target);let previous=null;try{previous=await fsp.readlink(currentLink)}catch{}const tmp=`${currentLink}.next`;await fsp.rm(tmp,{force:true,recursive:true});await fsp.symlink(target,tmp,process.platform==='win32'?'junction':'dir');await fsp.rename(tmp,currentLink);return{target,previous,currentLink}}
  async rollback(install){if(!install?.previous)return false;const tmp=`${install.currentLink}.rollback`;await fsp.rm(tmp,{force:true,recursive:true});await fsp.symlink(install.previous,tmp,process.platform==='win32'?'junction':'dir');await fsp.rm(install.currentLink,{force:true,recursive:true});await fsp.rename(tmp,install.currentLink);return true}
  async checkNow(){if(!this.enabled||this.running)return{skipped:true,reason:this.enabled?'RUNNING':'DISABLED'};this.running=true;let deploymentId=null,install=null;try{const m=await this.manifest();if(!m?.updateAvailable)return{updated:false};deploymentId=m.deployment.id;const work=path.join(this.dataDir,'updates',deploymentId),zip=path.join(work,'release.zip'),staged=path.join(work,'staged');await fsp.mkdir(work,{recursive:true});await this.report(deploymentId,'DOWNLOADING');await this.download(m.release.artifactUrl,zip);const actual=await sha256File(zip);if(actual.toLowerCase()!==String(m.release.sha256).toLowerCase())throw Object.assign(new Error('SHA-256 del update no coincide'),{code:'EDGE_UPDATE_HASH_MISMATCH'});const backupPath=await this.backup(deploymentId,m.deployment.previousVersion);await this.extract(zip,staged);await this.report(deploymentId,'INSTALLING',{backupPath});install=await this.atomicInstall(staged,m.deployment);await this.report(deploymentId,'HEALTHCHECK',{backupPath});await this.healthCheck();await this.report(deploymentId,'SUCCESS',{backupPath,evidence:{sha256:actual,target:install.target}});return{updated:true,version:m.release.version}}catch(error){if(deploymentId){let rolled=false;try{rolled=await this.rollback(install)}catch{}await this.report(deploymentId,rolled?'ROLLED_BACK':'FAILED',{errorCode:error.code||'EDGE_UPDATE_FAILED',errorMessage:error.message,evidence:{rollback:rolled}})}throw error}finally{this.running=false}}
}
module.exports={EdgeUpdater,sha256File};
