const rbac = require('../platform/rbac/rbac.service');

const RESTAURANT_MODULES = ['RESTAURANTE', 'MESAS', 'PEDIDOS', 'COMANDAS', 'DOMICILIOS'];

const RESTAURANT_ROLES = {
  MESERO: [
    'DASHBOARD.VER', 'RESTAURANTE.VER',
    'MESAS.VER', 'MESAS.CREAR', 'MESAS.EDITAR',
    'PEDIDOS.VER', 'PEDIDOS.CREAR',
    'COMANDAS.VER',
    'DOMICILIOS.VER', 'DOMICILIOS.CREAR', 'DOMICILIOS.EDITAR'
  ],
  COCINA: ['RESTAURANTE.VER', 'COMANDAS.VER', 'COMANDAS.EDITAR'],
  BARRA: ['RESTAURANTE.VER', 'COMANDAS.VER', 'COMANDAS.EDITAR'],
  POSTRES: ['RESTAURANTE.VER', 'COMANDAS.VER', 'COMANDAS.EDITAR'],
  CAJERO: [
    'DASHBOARD.VER',
    'RESTAURANTE.VER', 'RESTAURANTE.CERRAR',
    'MESAS.VER',
    'PEDIDOS.VER',
    'COMANDAS.VER',
    'DOMICILIOS.VER', 'DOMICILIOS.CREAR', 'DOMICILIOS.EDITAR', 'DOMICILIOS.PAGAR',
    'TESORERIA.VER', 'TESORERIA.CREAR', 'TESORERIA.CERRAR', 'TESORERIA.PAGAR'
  ]
};

let installed = false;

function installRestaurantRbac() {
  if (installed) return;
  rbac.registerVerticalRbac('RESTAURANT', RESTAURANT_MODULES, RESTAURANT_ROLES);
  installed = true;
}

module.exports = { RESTAURANT_MODULES, RESTAURANT_ROLES, installRestaurantRbac };
