/* VANTIX_RESTAURANT_V2_KDS_P6 */
(()=>{'use strict';
const RV2=window.RestaurantV2;if(!RV2)throw new Error('Restaurant V2 SDK no disponible');
const session=RV2.requireSession();const S={data:null,station:new URLSearchParams(location.search).get('station'),known:new Set(),loading:false,reloadQueued:false,pendingAction:null,soundUnlocked:false};
const $=q=>document.querySelector(q);const $$=q=>[...document.querySelectorAll(q)];
const esc=RV2.esc;
function setNotice(text,error=false){$('#notice').textContent=text;$('#notice').style.color=error?'#991b1b':''}
function age(row){const d=new Date(row?.creadoEn||0).getTime();if(!d)return'—';const m=Math.max(0,Math.floor((Date.now()-d)/60000));return m<1?'ahora':m<60?`${m} min`:`${Math.floor(m/60)} h ${m%60} min`}
function tableName(c){return c.order?.session?.table?.name||c.order?.session?.table?.code||'Mesa'}
function items(c){return(c.order?.items||[]).filter(item=>!item.station||item.station===c.station)}
function nextAction(state){return state==='PENDIENTE'?['EN_PREPARACION','TOMAR COMANDA']:state==='EN_PREPARACION'?['LISTA','✓ MARCAR LISTO']:state==='LISTA'?['ENTREGADA','MARCAR ENTREGADO']:null}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.12,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.24);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.27);o.onended=()=>ctx.close?.()}catch{}}
function ticket(c){const action=nextAction(c.state);return `<article class="ticket ${esc(c.state)}" id="command-${esc(c.id)}"><div class="ticket-head"><div><h3>${esc(tableName(c))}</h3><p>${esc(age(c))} · ${esc(c.station||'')}</p></div><span class="state">${esc(String(c.state||'').replaceAll('_',' '))}</span></div><div>${items(c).map(i=>`<div class="item"><strong>${esc(i.quantity)}×</strong> ${esc(i.description||'Producto')}${i.seatNumber?`<span class="person">PERSONA ${esc(i.seatNumber)}</span>`:''}${i.notes?`<span class="note">NOTA: ${esc(i.notes)}</span>`:''}</div>`).join('')||'<div class="item">Sin productos visibles.</div>'}</div>${action?`<button class="rv2-btn rv2-btn-primary ticket-action" type="button" data-command="${esc(c.id)}" data-state="${action[0]}">${action[1]}</button>`:''}</article>`}
function renderLane(state,id){const rows=(S.data?.commands||[]).filter(c=>c.state===state);$(id).innerHTML=rows.length?rows.map(ticket).join(''):`<div class="empty">Sin comandas ${state==='PENDIENTE'?'pendientes':state==='EN_PREPARACION'?'en preparación':'listas'}.</div>`;return rows.length}
function renderQueues(){const rows=S.data?.queues||[];$('#queues').innerHTML=rows.map(q=>`<button type="button" class="queue-tab ${q.queue===S.data.selectedStation?'active':''}" data-queue="${esc(q.queue)}"><b>${esc(q.label)}</b><small class="${q.preferred?'preferred':''}">${q.preferred?'★ Principal · ':''}${q.configured?q.stations.map(s=>esc(s.name)).join(' · '):'Sin KDS configurado'}</small></button>`).join('');$$('[data-queue]').forEach(b=>b.onclick=()=>switchQueue(b.dataset.queue))}
function render(){if(!S.data)return;S.station=S.data.selectedStation;renderQueues();const a=renderLane('PENDIENTE','#pendingLane'),b=renderLane('EN_PREPARACION','#preparingLane'),c=renderLane('LISTA','#readyLane');$('#pendingCount').textContent=$('#pendingBadge').textContent=a;$('#preparingCount').textContent=$('#preparingBadge').textContent=b;$('#readyCount').textContent=$('#readyBadge').textContent=c;$('#activeCount').textContent=a+b+c;const queue=S.data.queues.find(q=>q.queue===S.data.selectedStation);$('#stationWarning').hidden=Boolean(queue?.configured);if(!queue?.configured){$('#stationWarning').textContent=`${queue?.label||S.data.selectedStation}: no existe una estación KDS activa. Las comandas se muestran como rescate operativo para no ocultar trabajo pendiente.`}$$('[data-command]').forEach(b=>b.onclick=()=>askState(b.dataset.command,b.dataset.state));const target=new URLSearchParams(location.search).get('command');if(target)document.getElementById(`command-${target}`)?.scrollIntoView({block:'center'})}
async function load(reason='manual'){if(S.loading){S.reloadQueued=true;return}S.loading=true;try{const q=S.station?`?station=${encodeURIComponent(S.station)}`:'';const data=await RV2.api(`/api/v1/restaurante/v2/kds${q}`);const next=new Set((data.commands||[]).filter(c=>c.state==='PENDIENTE').map(c=>c.id));if(S.known.size&&[...next].some(id=>!S.known.has(id)))beep();S.known=next;S.data=data;$('#tenantLine').textContent=`${session.tenant?.nombreEmpresa||session.subdomain} · ${data.selectedStation} · Push V65 best-effort`;render();setNotice(reason==='realtime'?'Actualizado por evento en tiempo real.':'KDS V2 operativo.')}catch(e){setNotice(e.message||'No fue posible cargar KDS V2',true)}finally{S.loading=false;if(S.reloadQueued){S.reloadQueued=false;queueMicrotask(()=>load('realtime'))}}}
async function switchQueue(queue){if(queue===S.station)return;S.station=queue;S.known=new Set();const u=new URL(location.href);u.searchParams.set('station',queue);u.searchParams.delete('command');history.replaceState(null,'',u);await load('manual')}
function askState(id,state){const c=(S.data?.commands||[]).find(x=>x.id===id);if(!c)return;S.pendingAction={id,state};$('#confirmTitle').textContent=state==='EN_PREPARACION'?'Tomar comanda':state==='LISTA'?'Marcar comanda lista':'Marcar comanda entregada';$('#confirmText').textContent=`${tableName(c)} · ${c.station}. Se registrará ${String(c.state).replaceAll('_',' ')} → ${String(state).replaceAll('_',' ')}.`;$('#confirmDialog').showModal()}
async function confirmState(){const action=S.pendingAction;if(!action)return;$('#confirmAction').disabled=true;try{await RV2.api(`/api/v1/restaurante/v2/kds/comandas/${encodeURIComponent(action.id)}`,{method:'PATCH',body:JSON.stringify({state:action.state})});$('#confirmDialog').close();S.pendingAction=null;await load('manual')}catch(e){setNotice(e.message||'No fue posible cambiar la comanda',true)}finally{$('#confirmAction').disabled=false}}
function realtimeEvent(event){const topics=event?.detail?.topics||[];if(topics.includes('restaurant.command')||topics.includes('restaurant.order')||topics.includes('restaurant'))load('realtime')}
$('#refresh').onclick=()=>load('manual');$('#cancelAction').onclick=()=>{$('#confirmDialog').close();S.pendingAction=null};$('#confirmAction').onclick=confirmState;window.addEventListener('vantix:tenant-realtime',realtimeEvent);window.addEventListener('vantix:tenant-realtime-ready',()=>{$('.live').classList.add('on');$('#liveText').textContent='TENANT_REALTIME_V1 · conectado'});window.addEventListener('online',()=>{$('.live').classList.add('on');$('#liveText').textContent='Conexión disponible'});window.addEventListener('offline',()=>{$('.live').classList.remove('on');$('#liveText').textContent='Sin conexión'});document.addEventListener('pointerdown',()=>{S.soundUnlocked=true},{once:true});load('manual');
})();