/* VANTIX_RESTAURANT_V2_CASH_P4 */
(()=>{'use strict';
const RV2=window.RestaurantV2;if(!RV2)throw new Error('Restaurant V2 SDK no disponible');
const session=RV2.requireSession();
const S={workspace:null,detail:null,tableId:null,methodId:null,customerId:null,customers:[],filter:'READY',busy:false,searchTimer:null};
const $=q=>document.querySelector(q);const $$=q=>[...document.querySelectorAll(q)];
function notice(text,error=false){const node=$('#notice');node.textContent=text;node.classList.toggle('error',error)}
function selectedMethod(){return S.detail?.paymentMethods?.find(x=>x.id===S.methodId)||null}
function selectedCustomer(){return S.customers.find(x=>x.id===S.customerId)||null}
function methodLabel(kind){return kind==='EFECTIVO'?'Efectivo':kind==='TRANSFERENCIA'?'Transferencia / QR':kind==='TARJETA'?'Tarjeta':kind==='CREDITO'?'Crédito':kind}
function shiftExpected(shift){return Number(shift?.saldoInicial||0)+Number(shift?.ingresosEfectivo||0)-Number(shift?.egresosEfectivo||0)}
function renderShift(){const data=S.workspace?.shift||{};const own=data.own;const history='<a class="rv2-btn" href="/app/restaurante-v2/cierres">Cierres</a>';const panel=$('#shiftPanel');if(!own){panel.innerHTML=`<div class="shift-row"><div class="shift-meta"><span class="shift-icon">$</span><div><b>Turno de Caja cerrado</b><span>Abre tu turno para habilitar cobros reales.</span></div></div><div class="shift-actions">${history}<button id="openShift" class="rv2-btn rv2-btn-primary" type="button" ${data.cashAccounts?.length?'':'disabled'}>ABRIR TURNO</button></div></div>`;$('#openShift')?.addEventListener('click',showOpenShift);return}panel.innerHTML=`<div class="shift-row"><div class="shift-meta"><span class="shift-icon">✓</span><div><b>${RV2.esc(own.cajaBanco?.nombre||'Turno de Caja abierto')}</b><span>Abierto ${new Date(own.abiertoEn).toLocaleString('es-CO')} · ${RV2.esc(own.user?.nombre||'')}</span></div></div><div class="shift-actions">${history}<div class="shift-amount"><small>Efectivo esperado</small><strong>${RV2.money(shiftExpected(own))}</strong></div><button id="closeShift" class="rv2-btn" type="button">Cerrar turno</button></div></div>`;$('#closeShift').onclick=showCloseShift}
function queueRows(){const rows=S.workspace?.queue||[];return S.filter==='READY'?rows.filter(x=>x.readyForCash):rows}
function renderQueue(){const rows=queueRows();$('#queueCount').textContent=String(rows.length);$('#queue').innerHTML=rows.map(row=>`<button class="queue-item ${row.readyForCash?'ready':''} ${row.table.id===S.tableId?'active':''}" data-table="${RV2.esc(row.table.id)}" type="button"><div><header><span class="state-dot"></span><b>${RV2.esc(row.table.name||row.table.code)}</b></header><small>${row.readyForCash?'Cuenta solicitada':'Servicio activo'} · ${Number(row.guestCount||1)} persona(s)</small>${row.requiresP5?'<span class="p5">REQUIERE DIVISIÓN P5</span>':''}</div><strong>${RV2.money(row.sale?.total||0)}</strong></button>`).join('')||'<div class="rv2-muted">No hay mesas en este filtro.</div>';$$('[data-table]').forEach(button=>button.onclick=()=>selectTable(button.dataset.table));}
function renderPaymentMethods(){const methods=S.detail?.paymentMethods||[];if(!methods.some(x=>x.id===S.methodId))S.methodId=methods[0]?.id||null;$('#paymentMethods').innerHTML=methods.map(method=>`<button class="method-btn ${method.id===S.methodId?'active':''}" data-method="${RV2.esc(method.id)}" type="button"><b>${RV2.esc(method.name)}</b><span>${RV2.esc(methodLabel(method.kind))}${method.account?.nombre?` · ${RV2.esc(method.account.nombre)}`:''}</span></button>`).join('')||'<div class="rv2-muted">No hay métodos de pago activos.</div>';$$('[data-method]').forEach(button=>button.onclick=()=>{S.methodId=button.dataset.method;S.customerId=null;renderPaymentMethods();renderPaymentFields();});renderPaymentFields()}
function renderPaymentFields(){const method=selectedMethod();const credit=method?.kind==='CREDITO';$('#creditBox').hidden=!credit;$('#tipAmount').disabled=credit;$('#tipAmount').value=credit?'0':$('#tipAmount').value||'0';const reference=$('#referenceLabel');reference.hidden=!method||['EFECTIVO'].includes(method.kind);$('#paymentReference').placeholder=method?.kind==='TRANSFERENCIA'?'Número de comprobante (opcional)':method?.kind==='TARJETA'?'Voucher / autorización (opcional)':'Referencia (opcional)';if(credit&&!S.customers.length)loadCustomers('');renderChargeState()}
function renderCustomers(){const current=selectedCustomer();$('#customers').innerHTML=S.customers.map(customer=>`<button class="customer-row ${customer.id===S.customerId?'active':''}" data-customer="${RV2.esc(customer.id)}" type="button"><b>${RV2.esc(customer.nombre||customer.razonSocial||'Cliente')}</b><small>${RV2.esc(customer.identificacion||'')} · cupo ${RV2.money(customer.cupoCredito||0)} · ${Number(customer.diasPlazo||0)} días</small></button>`).join('')||'<div class="rv2-muted">No hay clientes que coincidan.</div>';$$('[data-customer]').forEach(button=>button.onclick=()=>{S.customerId=button.dataset.customer;renderCustomers();renderChargeState()});if(current&&!S.customers.some(x=>x.id===current.id))S.customerId=null}
function renderChargeState(){const method=selectedMethod();const requiresP5=Boolean(S.detail?.session?.requiresP5);const ownShift=Boolean(S.workspace?.shift?.own);const needsCustomer=method?.kind==='CREDITO'&&!S.customerId;const disabled=S.busy||!S.detail||!method||!ownShift||requiresP5||needsCustomer;$('#charge').disabled=disabled;$('#charge').textContent=requiresP5?'DIVISIÓN V2 P5 REQUERIDA':method?.kind==='CREDITO'&&!S.customerId?'SELECCIONA CLIENTE PARA CRÉDITO':'COBRAR CUENTA COMPLETA'}
function renderDetail(){const data=S.detail;$('#emptyDetail').hidden=Boolean(data);$('#detail').hidden=!data;if(!data)return;$('#detailCode').textContent=data.table.code||'MESA';$('#detailName').textContent=data.table.name||data.table.code;$('#detailState').textContent=`${data.session.state} · ${Number(data.session.guestCount||1)} persona(s) · ${data.session.billingMode||'CONJUNTA'}`;$('#detailTotal').textContent=RV2.money(data.sale.total);$('#saleNumber').textContent=data.sale.numero||'Venta en curso';$('#subtotal').textContent=RV2.money(data.sale.subtotal);$('#iva').textContent=RV2.money(data.sale.ivaTotal);$('#impoconsumo').textContent=RV2.money(data.sale.impoconsumoTotal);$('#billTotal').textContent=RV2.money(data.sale.total);$('#posMode').textContent=data.operation?.dianEnabled?'POS + DIAN OPCIONAL':'POS INTERNO';$('#splitWarning').hidden=!data.session.requiresP5;$('#items').innerHTML=(data.sale.items||[]).map(item=>`<div class="bill-item"><b>${RV2.esc(item.description)}</b><span>${Number(item.quantity||0)} × ${RV2.money(item.unitPrice)}</span><strong>${RV2.money(item.total)}</strong></div>`).join('')||'<div class="rv2-muted">La cuenta no tiene productos.</div>';renderPaymentMethods()}
function renderAll(){renderShift();renderQueue();renderDetail();$$('[data-filter]').forEach(button=>button.classList.toggle('active',button.dataset.filter===S.filter))}
async function loadWorkspace(preserve=true){if(S.busy)return;S.busy=true;try{notice('Actualizando Caja V2…');S.workspace=await RV2.api('/api/v1/restaurante/v2/caja');$('#restaurantName').textContent=session.tenant?.nombreEmpresa||'Caja';$('#tenantLine').textContent=`${session.subdomain} · ${S.workspace.operation.mode} · DIAN ${S.workspace.operation.dianEnabled?'conectada':'opcional / apagada'}`;if(!preserve||!S.workspace.queue.some(x=>x.table.id===S.tableId)){S.tableId=null;S.detail=null;S.methodId=null;S.customerId=null}renderAll();notice(S.workspace.shift.own?'Caja V2 operativa · turno abierto':'Caja V2 lista · abre un turno para cobrar');if(S.tableId)await loadDetail(S.tableId)}catch(error){notice(error.message||'No fue posible cargar Caja V2',true)}finally{S.busy=false;renderChargeState()}}
async function selectTable(tableId){S.tableId=tableId;S.methodId=null;S.customerId=null;S.customers=[];renderQueue();await loadDetail(tableId)}
async function loadDetail(tableId){try{notice('Cargando cuenta…');S.detail=await RV2.api(`/api/v1/restaurante/v2/caja/mesas/${encodeURIComponent(tableId)}`);renderDetail();notice(S.detail.session.requiresP5?'Cuenta detectada: requiere División V2 P5.':'Cuenta completa lista para cobro.')}catch(error){S.detail=null;renderDetail();notice(error.message,true)}}
function showOpenShift(){const accounts=S.workspace?.shift?.cashAccounts||[];$('#cashAccount').innerHTML=accounts.map(row=>`<option value="${RV2.esc(row.id)}">${RV2.esc(row.nombre)} · saldo ${RV2.money(row.saldoActual)}</option>`).join('');$('#initialBalance').value='0';$('#openShiftDialog').showModal()}
async function openShift(event){event.preventDefault();if(S.busy)return;S.busy=true;try{await RV2.api('/api/v1/restaurante/v2/caja/turno/abrir',{method:'POST',body:JSON.stringify({cajaBancoId:$('#cashAccount').value,saldoInicial:Number($('#initialBalance').value||0)})});$('#openShiftDialog').close();notice('Turno de Caja abierto.')}catch(error){notice(error.message,true)}finally{S.busy=false}await loadWorkspace()}
async function showCloseShift(){if(S.busy)return;try{const data=await RV2.api('/api/v1/restaurante/v2/caja/turno/resumen');$('#shiftSummary').innerHTML=`<div><small>Ventas del turno</small><b>${RV2.money(data.restaurantClosedTablesTotal)}</b></div><div><small>Efectivo sistema</small><b>${RV2.money(data.systemCashExpected)}</b></div><div><small>Efectivo ventas</small><b>${RV2.money(data.restaurantCashRecorded)}</b></div>`;$('#finalBalance').value=String(Number(data.systemCashExpected||0));$('#closeShiftDialog').showModal()}catch(error){notice(error.message,true)}}
async function closeShift(event){event.preventDefault();if(S.busy)return;if(!confirm('¿Cerrar el turno con el efectivo contado indicado?'))return;const printReceipt=confirm('¿Imprimir también la tirilla completa del cierre de turno?');S.busy=true;try{const data=await RV2.api('/api/v1/restaurante/v2/caja/turno/cerrar',{method:'POST',body:JSON.stringify({saldoFinal:Number($('#finalBalance').value||0),printReceipt,tzOffsetMinutes:new Date().getTimezoneOffset()})});$('#closeShiftDialog').close();const saved=data.closeHistory?.persisted?'Cierre guardado.':'El turno cerró; el historial se regenerará al consultarlo.';const printed=printReceipt?(data.closeReceipt?.queued?' Tirilla enviada a impresión.':' La tirilla no pudo encolarse; puede reimprimirse desde Cierres.'):'';
notice(`Turno cerrado. Descuadre: ${RV2.money(data.closed.descuadre||0)}. ${saved}${printed}`)}catch(error){notice(error.message,true)}finally{S.busy=false}await loadWorkspace(false)}
async function loadCustomers(q){try{S.customers=await RV2.api(`/api/v1/restaurante/v2/caja/clientes?q=${encodeURIComponent(q||'')}`);renderCustomers()}catch(error){notice(error.message,true)}}
function scheduleCustomerSearch(){clearTimeout(S.searchTimer);S.searchTimer=setTimeout(()=>loadCustomers($('#customerSearch').value),220)}
async function createCustomer(event){event.preventDefault();if(S.busy)return;const fd=new FormData(event.currentTarget);const payload={};for(const [key,value] of fd.entries())payload[key]=typeof value==='string'?value.trim():value;payload.cupoCredito=Number(payload.cupoCredito||0);payload.diasPlazo=Number(payload.diasPlazo||0);for(const key of ['telefono','email'])if(!payload[key])payload[key]=null;S.busy=true;try{const customer=await RV2.api('/api/v1/restaurante/v2/caja/clientes',{method:'POST',body:JSON.stringify(payload)});S.customerId=customer.id;$('#customerDialog').close();event.currentTarget.reset();S.customers=await RV2.api(`/api/v1/restaurante/v2/caja/clientes?q=${encodeURIComponent(customer.identificacion||customer.nombre||'')}`);if(!S.customers.some(x=>x.id===customer.id))S.customers.unshift(customer);renderCustomers();renderChargeState();notice('Cliente creado y seleccionado para crédito.')}catch(error){notice(error.message,true)}finally{S.busy=false;renderChargeState()}}
async function charge(){const method=selectedMethod();if(!S.detail||!method||S.busy)return;const customer=selectedCustomer();const total=RV2.money(S.detail.sale.total);const customerText=method.kind==='CREDITO'?` a crédito para ${customer?.nombre||'cliente'}`:'';if(!confirm(`Se registrará un cobro real de ${total} con ${method.name}${customerText}. ¿Continuar?`))return;S.busy=true;renderChargeState();try{const payload={paymentMethodId:method.id,tipAmount:Number($('#tipAmount').value||0),reference:$('#paymentReference').value.trim()||null,terceroId:method.kind==='CREDITO'?S.customerId:null};const data=await RV2.api(`/api/v1/restaurante/v2/caja/mesas/${encodeURIComponent(S.detail.table.id)}/cobrar`,{method:'POST',body:JSON.stringify(payload)});const saleNumber=data.result?.sale?.numero||'POS';const queued=Boolean(data.result?.posReceipt?.queued);$('#resultTitle').textContent=`${saleNumber} · ${method.name}`;$('#resultText').textContent=`Cobro registrado en el Core. ${queued?'Tirilla POS enviada a la cola de impresión.':'La venta quedó registrada; la cola de impresión no confirmó el encolado.'}${data.credit?.dueDate?` Vence ${new Date(data.credit.dueDate).toLocaleDateString('es-CO')}.`:''}`;$('#resultDialog').showModal();S.tableId=null;S.detail=null;S.methodId=null;S.customerId=null;S.customers=[]}catch(error){notice(error.message,true)}finally{S.busy=false;renderChargeState()}await loadWorkspace(false)}
$('#refresh').onclick=()=>loadWorkspace();$$('[data-filter]').forEach(button=>button.onclick=()=>{S.filter=button.dataset.filter;renderAll()});$('#openShiftForm').addEventListener('submit',openShift);$('#closeShiftForm').addEventListener('submit',closeShift);$('#customerForm').addEventListener('submit',createCustomer);$('#customerSearch').addEventListener('input',scheduleCustomerSearch);$('#newCustomer').onclick=()=>$('#customerDialog').showModal();$('#charge').onclick=charge;$('#resultClose').onclick=()=>$('#resultDialog').close();$$('[data-close]').forEach(button=>button.onclick=()=>document.getElementById(button.dataset.close)?.close());window.addEventListener('vantix:tenant-realtime',()=>loadWorkspace());window.addEventListener('pageshow',()=>loadWorkspace());loadWorkspace(false);
})();