/* VANTIX_RESTAURANT_P13_E5_CASH_HISTORY */
(()=>{'use strict';
const MARKER='VANTIX_RESTAURANT_P13_E5_CASH_HISTORY';
if(window[MARKER])return;
window[MARKER]=Object.freeze({version:'5.0.0',local:true,readOnlyDocuments:true,reprintCopy:true});
if(location.pathname!=='/app/restaurante-v2/caja')return;
const RV2=window.RestaurantV2;
if(!RV2)return;
const $=(q,r=document)=>r.querySelector(q);
const esc=(v)=>RV2.esc(v);
const money=(v)=>RV2.money(Number(v||0));

function style(){
 if($('#p13CashHistoryStyle'))return;
 const s=document.createElement('style');s.id='p13CashHistoryStyle';s.textContent=`
 .p13-history{margin-top:16px}.p13-history-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px}.p13-history-head small{display:block;color:#64748b;font-size:10px;font-weight:800;letter-spacing:.08em}.p13-history-head h2{margin:2px 0 0;font-size:18px}.p13-history-list{display:grid;gap:8px}.p13-sale-row{width:100%;border:1px solid #dbe3eb;border-radius:13px;background:#fff;padding:11px 13px;text-align:left;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:4px 12px;cursor:pointer;color:#17212b}.p13-sale-row:hover{border-color:#9fb0be;background:#f8fafc}.p13-sale-row b{font-size:14px}.p13-sale-row strong{font-size:15px}.p13-sale-row small{grid-column:1/-1;color:#64748b}.p13-history-empty{padding:14px;border:1px dashed #cbd5e1;border-radius:12px;color:#64748b;text-align:center}
 #p13SaleDialog{border:0;border-radius:18px;padding:0;max-width:680px;width:calc(100% - 24px);box-shadow:0 24px 80px rgba(15,23,42,.25)}#p13SaleDialog::backdrop{background:rgba(15,23,42,.45)}.p13-doc{padding:18px;display:grid;gap:14px}.p13-doc-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.p13-doc-head small{display:block;color:#64748b;font-size:10px;font-weight:800}.p13-doc-head h2{margin:3px 0 0}.p13-doc-total{font-size:22px;font-weight:900}.p13-doc-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.p13-doc-meta div{padding:9px 10px;border:1px solid #e2e8f0;border-radius:11px}.p13-doc-meta small{display:block;color:#64748b}.p13-doc-items{border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.p13-doc-item{display:grid;grid-template-columns:64px minmax(0,1fr) auto;gap:8px;padding:9px 11px;border-bottom:1px solid #eef2f7;align-items:center}.p13-doc-item:last-child{border-bottom:0}.p13-doc-item span:last-child{text-align:right}.p13-doc-totals{display:grid;gap:6px}.p13-doc-totals div{display:flex;justify-content:space-between;gap:10px}.p13-doc-actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}.p13-copy-note{padding:9px 11px;background:#f8fafc;border-radius:10px;color:#475569;font-size:12px}
 @media(max-width:620px){.p13-doc-meta{grid-template-columns:1fr}.p13-doc-item{grid-template-columns:52px minmax(0,1fr);}.p13-doc-item span:last-child{grid-column:2}.p13-doc-actions{justify-content:stretch}.p13-doc-actions button{flex:1}}
 `;document.head.appendChild(s);
}
function dateTime(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':new Intl.DateTimeFormat('es-CO',{dateStyle:'short',timeStyle:'short'}).format(d)}
function ensureUi(){
 style();const main=$('.cash-main');if(!main)return null;
 let panel=$('#p13CashHistory');if(!panel){panel=document.createElement('section');panel.id='p13CashHistory';panel.className='rv2-panel p13-history';panel.innerHTML=`<div class="p13-history-head"><div><small>CAJA LOCAL</small><h2>Últimos cobros</h2></div><button id="p13RefreshHistory" class="rv2-btn" type="button">Actualizar</button></div><div id="p13CashHistoryList" class="p13-history-list"><div class="p13-history-empty">Cargando ventas liquidadas…</div></div>`;main.appendChild(panel);$('#p13RefreshHistory',panel)?.addEventListener('click',loadHistory)}
 let dialog=$('#p13SaleDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='p13SaleDialog';dialog.innerHTML='<div id="p13SaleDocument" class="p13-doc"></div>';document.body.appendChild(dialog)}
 return {panel,dialog};
}
async function loadHistory(){
 const ui=ensureUi();if(!ui)return;const list=$('#p13CashHistoryList',ui.panel);list.innerHTML='<div class="p13-history-empty">Cargando…</div>';
 try{const data=await RV2.api('/api/v1/restaurante/p13-local/caja/ultimos-cobros?limit=15');const rows=data?.rows||[];if(!rows.length){list.innerHTML='<div class="p13-history-empty">Todavía no hay cobros liquidados en esta base local.</div>';return}list.innerHTML=rows.map(r=>`<button class="p13-sale-row" type="button" data-p13-session="${esc(r.sessionId)}"><b>${esc(r.saleNumber||'Venta')}</b><strong>${money(r.total)}</strong><small>${esc(r.table?.name||r.table?.code||'Venta')} · ${esc(r.paymentMethodLabel||r.paymentMethodKind||r.paymentForm||'Pago')} · ${esc(dateTime(r.closedAt))}</small></button>`).join('');list.querySelectorAll('[data-p13-session]').forEach(btn=>btn.addEventListener('click',()=>openDocument(btn.dataset.p13Session)))}catch(error){list.innerHTML=`<div class="p13-history-empty">${esc(error.message||'No fue posible cargar los cobros.')}</div>`}
}
async function openDocument(sessionId){
 const ui=ensureUi();const box=$('#p13SaleDocument',ui.dialog);box.innerHTML='<div class="p13-history-empty">Cargando documento…</div>';ui.dialog.showModal();
 try{const d=await RV2.api(`/api/v1/restaurante/p13-local/caja/documentos/${encodeURIComponent(sessionId)}`);const sale=d.sale||{},session=d.session||{};box.innerHTML=`<div class="p13-doc-head"><div><small>DOCUMENTO LIQUIDADO · SOLO LECTURA</small><h2>${esc(sale.number||'Venta')}</h2><span>${esc(session.table?.name||session.table?.code||'')}</span></div><div class="p13-doc-total">${money(sale.total)}</div></div><div class="p13-doc-meta"><div><small>Fecha / hora</small><b>${esc(dateTime(session.closedAt||sale.emittedAt||sale.date))}</b></div><div><small>Método de pago</small><b>${esc(session.paymentMethodLabel||session.paymentMethodKind||sale.paymentForm||'—')}</b></div><div><small>Cajero</small><b>${esc(session.cashier?.name||session.cashier?.email||'—')}</b></div><div><small>Referencia</small><b>${esc(session.paymentReference||'—')}</b></div></div><div class="p13-doc-items">${(sale.items||[]).map(i=>`<div class="p13-doc-item"><span>${esc(i.quantity)} x</span><span><b>${esc(i.description)}</b><br><small>${money(i.unitPrice)} c/u</small></span><span>${money(i.total)}</span></div>`).join('')||'<div class="p13-history-empty">Sin productos.</div>'}</div><div class="p13-doc-totals"><div><span>Subtotal</span><b>${money(sale.subtotal)}</b></div><div><span>IVA</span><b>${money(sale.iva)}</b></div><div><span>Impoconsumo</span><b>${money(sale.impoconsumo)}</b></div>${Number(session.tipAmount||0)>0?`<div><span>Propina</span><b>${money(session.tipAmount)}</b></div>`:''}<div><strong>Total</strong><strong>${money(sale.total)}</strong></div></div><div class="p13-copy-note">Reimprimir genera únicamente una COPIA de esta venta. No vuelve a cobrar ni modifica inventario, Caja, Tesorería o Contabilidad.</div><div class="p13-doc-actions"><button id="p13CloseDoc" class="rv2-btn" type="button">CERRAR</button><button id="p13ReprintDoc" class="rv2-btn rv2-btn-primary" type="button">REIMPRIMIR COPIA</button></div>`;$('#p13CloseDoc',box)?.addEventListener('click',()=>ui.dialog.close());$('#p13ReprintDoc',box)?.addEventListener('click',()=>reprint(sessionId,box))}catch(error){box.innerHTML=`<div class="p13-history-empty">${esc(error.message||'No fue posible abrir el documento.')}</div><div class="p13-doc-actions"><button class="rv2-btn" type="button" id="p13CloseDoc">CERRAR</button></div>`;$('#p13CloseDoc',box)?.addEventListener('click',()=>ui.dialog.close())}
}
async function reprint(sessionId,box){
 const btn=$('#p13ReprintDoc',box);if(!btn)return;btn.disabled=true;const old=btn.textContent;btn.textContent='ENVIANDO…';
 try{const requestId=`cash-copy-${crypto.randomUUID()}`;const result=await RV2.api(`/api/v1/restaurante/p13-local/caja/documentos/${encodeURIComponent(sessionId)}/reimprimir`,{method:'POST',body:JSON.stringify({requestId})});btn.textContent=result?.duplicate?'COPIA YA EN COLA':'COPIA EN COLA';setTimeout(()=>{btn.disabled=false;btn.textContent=old},1800)}catch(error){btn.disabled=false;btn.textContent=old;alert(error.message||'No fue posible enviar la copia a impresión.')}
}
window.addEventListener('pageshow',()=>setTimeout(loadHistory,250));window.addEventListener('vantix:restaurant-v2:cash-updated',()=>setTimeout(loadHistory,100));ensureUi();setTimeout(loadHistory,350);
})();
